// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV5ooskDduAzjGcLyPUiDPl6o73eFhUgg',
    appId: '1:928654257374:web:7992c1d44c2c76e354a64f',
    messagingSenderId: '928654257374',
    projectId: 'image-uploader-bloc',
    authDomain: 'image-uploader-bloc.firebaseapp.com',
    storageBucket: 'image-uploader-bloc.appspot.com',
    measurementId: 'G-8YBVD62776',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMOF2Bc1iOwIPp77E7UGA_Zlks40sGUB8',
    appId: '1:928654257374:android:e0e60d54cbec322754a64f',
    messagingSenderId: '928654257374',
    projectId: 'image-uploader-bloc',
    storageBucket: 'image-uploader-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvYEbAQ9cb3Vajar8P48rL3JV3wqjeqdU',
    appId: '1:928654257374:ios:9af70ebff99e77d654a64f',
    messagingSenderId: '928654257374',
    projectId: 'image-uploader-bloc',
    storageBucket: 'image-uploader-bloc.appspot.com',
    iosBundleId: 'com.example.imageUploader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvYEbAQ9cb3Vajar8P48rL3JV3wqjeqdU',
    appId: '1:928654257374:ios:b70cdec8bb1b5ddc54a64f',
    messagingSenderId: '928654257374',
    projectId: 'image-uploader-bloc',
    storageBucket: 'image-uploader-bloc.appspot.com',
    iosBundleId: 'com.example.imageUploader.RunnerTests',
  );
}
